// GENERATED by tools/linux/gen_family_getters.py from the build-35924 ELF
// (GNU build-id 3a0e156390b0e6f1e372051c24802c8493ae454a). Do not edit by hand.
//
// Every ECS family GetNodeList implementation (vtable slot 2). GCC keeps one
// copy per family template instantiation where MSVC folds them into one, so
// the native family canon must recognise each copy. Install verifies every
// entry byte for byte; the canon calls none of them.
#pragma once
#include <cstdint>

// `endbr64; lea rax,[rdi+8]; ret` -- the family holds a node list at +8.
static constexpr uintptr_t kFamilyListGetters[] = {
    0xa914c0,  // vtable 0x59ad080 N3ecs21ComponentGroupFamily1INS_9component14PersonCapacityEEE
    0xa914d0,  // vtable 0x59ad040 N3ecs21ComponentGroupFamily1INS_9component8ScaffoldEEE
    0xa91510,  // vtable 0x59acfc0 N3ecs21ComponentGroupFamily5INS_9component11RoadVehicleENS1_8MovePathENS1_17ModelInstanceListENS1_14BoundingVolumeENS1_12VehicleOrderEEE
    0xa91580,  // vtable 0x59acf00 N3ecs21ComponentGroupFamily1INS_9component8BaseEdgeEEE
    0xa91590,  // vtable 0x59acec0 N3ecs21ComponentGroupFamily1INS_9component14TownConnectionEEE
    0xa91600,  // vtable 0x59ace00 N3ecs21ComponentGroupFamily1INS_9component9StockListEEE
    0xa916d0,  // vtable 0x59accc0 N3ecs21ComponentGroupFamily1INS_9component16SimEntityAtStockEEE
    0xa916e0,  // vtable 0x59acc80 N3ecs21ComponentGroupFamily1INS_9component19SimEntityAtBuildingEEE
    0xa916f0,  // vtable 0x59acc40 N3ecs21ComponentGroupFamily1INS_9component11SimBuildingEEE
    0xa917c0,  // vtable 0x59acb00 N3ecs21ComponentGroupFamily1INS_9component12TownBuildingEEE
    0xa917d0,  // vtable 0x59acac0 N3ecs21ComponentGroupFamily1INS_9component4TownEEE
    0xa91840,  // vtable 0x59aca00 N3ecs21ComponentGroupFamily4INS_9component11ModelPersonENS1_17ModelInstanceListENS1_14BoundingVolumeENS1_12VehicleOrderEEE
    0xa91850,  // vtable 0x59ac9c0 N3ecs21ComponentGroupFamily4INS_9component4ShipENS1_16MovePathAircraftENS1_17ModelInstanceListENS1_14BoundingVolumeEEE
    0xa91860,  // vtable 0x59ac980 N3ecs21ComponentGroupFamily4INS_9component8AircraftENS1_16MovePathAircraftENS1_17ModelInstanceListENS1_14BoundingVolumeEEE
    0xa91870,  // vtable 0x59ac940 N3ecs21ComponentGroupFamily2INS_9component5TrainENS1_8MovePathEEE
    0xa91880,  // vtable 0x59ac900 N3ecs21ComponentGroupFamily5INS_9component4TramENS1_8MovePathENS1_17ModelInstanceListENS1_14BoundingVolumeENS1_12VehicleOrderEEE
    0xa91890,  // vtable 0x59ac8c0 N3ecs21ComponentGroupFamily4INS_9component11RoadVehicleENS1_8MovePathENS1_17ModelInstanceListENS1_14BoundingVolumeEEE
    0xa918a0,  // vtable 0x59ac880 N3ecs21ComponentGroupFamily1INS_9component16TransportVehicleEEE
    0xa918e0,  // vtable 0x59ac800 N3ecs21ComponentGroupFamily1INS_9component12StationGroupEEE
    0xa918f0,  // vtable 0x59ac7c0 N3ecs21ComponentGroupFamily1INS_9component7StationEEE
    0xa91900,  // vtable 0x59ac780 N3ecs21ComponentGroupFamily1INS_9component7AccountEEE
    0xa91910,  // vtable 0x59ac740 N3ecs21ComponentGroupFamily1INS_9component12VehicleDepotEEE
    0xa91920,  // vtable 0x59ac700 N3ecs21ComponentGroupFamily1INS_9component10SignalListEEE
    0xa91930,  // vtable 0x59ac6c0 N3ecs21ComponentGroupFamily1INS_9component16RailroadCrossingEEE
    0xa91940,  // vtable 0x59ac680 N3ecs21ComponentGroupFamily2INS_9component20BaseNodeTrafficLightENS1_17ModelInstanceListEEE
    0xa91980,  // vtable 0x59ac600 N3ecs21ComponentGroupFamily1INS_9component16TransportNetworkEEE
    0xa91990,  // vtable 0x59ac5c0 N3ecs21ComponentGroupFamily3INS_9component6AnimalENS1_17ModelInstanceListENS1_14BoundingVolumeEEE
    0xa919a0,  // vtable 0x59ac580 N3ecs21ComponentGroupFamily1INS_9component12ConstructionEEE
};

// `endbr64; xor eax,eax; ret` -- the family has no node list.
static constexpr uintptr_t kFamilyNoListGetters[] = {
    0xa90720,  // vtable 0x59ac220 N3ecs23AllEntitiesFamilyNoListE
    0xa91370,  // vtable 0x59ad240 N3ecs27ComponentGroupFamilyNoList1INS_9component14ParticleSystemEEE
    0xa913a0,  // vtable 0x59ad200 N3ecs27ComponentGroupFamilyNoList2INS_9component8GameTimeENS1_9GameSpeedEEE
    0xa913d0,  // vtable 0x59ad1c0 N3ecs27ComponentGroupFamilyNoList1INS_9component12EmissionGridEEE
    0xa91400,  // vtable 0x59ad180 N3ecs27ComponentGroupFamilyNoList2INS_9component11TerrainTileENS1_20TerrainTileHeightmapEEE
    0xa91430,  // vtable 0x59ad140 N3ecs27ComponentGroupFamilyNoList2INS_9component11TerrainTileENS1_16TerrainTileBrushEEE
    0xa91460,  // vtable 0x59ad100 N3ecs27ComponentGroupFamilyNoList1INS_9component7TerrainEEE
    0xa91490,  // vtable 0x59ad0c0 N3ecs27ComponentGroupFamilyNoList1INS_9component16TransportHistoryEEE
    0xa914e0,  // vtable 0x59ad000 N3ecs27ComponentGroupFamilyNoList1INS_9component12VehicleOrderEEE
    0xa91520,  // vtable 0x59acf80 N3ecs29OrComponentGroupFamilyNoList2INS_9component7StationENS1_12VehicleDepotEEE
    0xa91550,  // vtable 0x59acf40 N3ecs27ComponentGroupFamilyNoList1INS_9component16MovePathAircraftEEE
    0xa915a0,  // vtable 0x59ace80 N3ecs27ComponentGroupFamilyNoList1INS_9component10RunwayListEEE
    0xa915d0,  // vtable 0x59ace40 N3ecs27ComponentGroupFamilyNoList1INS_9component4NameEEE
    0xa91610,  // vtable 0x59acdc0 N3ecs27ComponentGroupFamilyNoList1INS_9component13SimEntityIdleEEE
    0xa91640,  // vtable 0x59acd80 N3ecs27ComponentGroupFamilyNoList1INS_9component18SimPersonAtVehicleEEE
    0xa91670,  // vtable 0x59acd40 N3ecs27ComponentGroupFamilyNoList1INS_9component18SimEntityAtVehicleEEE
    0xa916a0,  // vtable 0x59acd00 N3ecs27ComponentGroupFamilyNoList1INS_9component19SimEntityAtTerminalEEE
    0xa91700,  // vtable 0x59acc00 N3ecs27ComponentGroupFamilyNoList1INS_9component18SimCargoAtTerminalEEE
    0xa91730,  // vtable 0x59acbc0 N3ecs27ComponentGroupFamilyNoList1INS_9component19SimPersonAtTerminalEEE
    0xa91760,  // vtable 0x59acb80 N3ecs27ComponentGroupFamilyNoList1INS_9component9SimPersonEEE
    0xa91790,  // vtable 0x59acb40 N3ecs27ComponentGroupFamilyNoList1INS_9component8SimCargoEEE
    0xa917e0,  // vtable 0x59aca80 N3ecs27ComponentGroupFamilyNoList1INS_9component20TerrainAlignmentListEEE
    0xa91810,  // vtable 0x59aca40 N3ecs27ComponentGroupFamilyNoList1INS_9component6ParcelEEE
    0xa918b0,  // vtable 0x59ac840 N3ecs27ComponentGroupFamilyNoList1INS_9component4LineEEE
    0xa91950,  // vtable 0x59ac640 N3ecs27ComponentGroupFamilyNoList1INS_9component9TpNetLinkEEE
    0xa919b0,  // vtable 0x59ac540 N3ecs27ComponentGroupFamilyNoList1INS_9component17BaseParallelStripEEE
    0xa919e0,  // vtable 0x59ac500 N3ecs29OrComponentGroupFamilyNoList2INS_9component7StationENS1_16TransportNetworkEEE
    0xa91a10,  // vtable 0x59ac4c0 N3ecs29OrComponentGroupFamilyNoList2INS_9component8BaseNodeENS1_8BaseEdgeEEE
    0xa91a40,  // vtable 0x59ac480 N3ecs27ComponentGroupFamilyNoList2INS_9component14BoundingVolumeENS1_6AnimalEEE
    0xa91a70,  // vtable 0x59ac440 N3ecs27ComponentGroupFamilyNoList2INS_9component14BoundingVolumeENS1_17ModelInstanceListEEE
    0xa91aa0,  // vtable 0x59ac400 N3ecs27ComponentGroupFamilyNoList2INS_9component14BoundingVolumeENS1_7LotListEEE
    0xa91ad0,  // vtable 0x59ac3c0 N3ecs27ComponentGroupFamilyNoList1INS_9component9WaterMeshEEE
    0xa91b00,  // vtable 0x59ac380 N3ecs27ComponentGroupFamilyNoList1INS_9component9ShapeListEEE
    0xa91b30,  // vtable 0x59ac340 N3ecs27ComponentGroupFamilyNoList1INS_9component17ModelInstanceListEEE
    0xa91b60,  // vtable 0x59ac300 N3ecs27ComponentGroupFamilyNoList1INS_9component14BoundingVolumeEEE
};

static constexpr unsigned kFamilyListGetterCount = 28;
static constexpr unsigned kFamilyNoListGetterCount = 35;
static_assert(sizeof(kFamilyListGetters) / sizeof(kFamilyListGetters[0]) == kFamilyListGetterCount);
static_assert(sizeof(kFamilyNoListGetters) / sizeof(kFamilyNoListGetters[0]) == kFamilyNoListGetterCount);
