#!/usr/bin/env python3
"""Inventory every ECS family's GetNodeList implementation in the native ELF.

MSVC folds identical functions (/OPT:ICF), so on Windows every
ComponentGroupFamily<...>::GetNodeList is ONE function (0xba990, `lea rax,[rcx+8]`)
and every no-list family shares another (0xbdff0). GCC does not fold them: build
35924 has 28 separate copies of `endbr64; lea rax,[rdi+8]; ret` and 35 of
`endbr64; xor eax,eax; ret`, one per family template instantiation. The native
family canon recognised only the first of each (0xa914c0 PersonCapacity,
0xa914e0 VehicleOrder) and refused the other 61 families, so on the native build
27 of the 28 node lists were never put in entity order (live server log:
`families=63/63 lists=1 ... unknown/refused=61`).

Usage:
  gen_family_getters.py GAME_ELF            print the inventory
  gen_family_getters.py GAME_ELF --header   write native/linux/src/family_getters_linux.h
  gen_family_getters.py GAME_ELF --check    verify that header against the ELF (exit 1 on mismatch)

Requires pyelftools. Read-only on the ELF.
"""
from pathlib import Path
import re
import sys
from elftools.elf.elffile import ELFFile
from elftools.elf.relocation import RelocationSection

BUILD_ID = '3a0e156390b0e6f1e372051c24802c8493ae454a'
GET_LIST = bytes.fromhex('f30f1efa488d4708c3')   # endbr64; lea rax,[rdi+8]; ret
GET_NONE = bytes.fromhex('f30f1efa31c0c3')       # endbr64; xor eax,eax; ret
ROOT = Path(__file__).resolve().parents[2]
HEADER = ROOT / 'native/linux/src/family_getters_linux.h'


def inventory(path):
    with open(path, 'rb') as stream:
        elf = ELFFile(stream)
        assert any(n['n_desc'] == BUILD_ID for s in elf.iter_segments() if s['p_type'] == 'PT_NOTE'
                   for n in s.iter_notes() if n['n_type'] == 'NT_GNU_BUILD_ID'), 'not build 35924'
        loads = [s for s in elf.iter_segments() if s['p_type'] == 'PT_LOAD']
        stream.seek(0)
        blob = stream.read()

        def read(addr, size):
            for s in loads:
                if s['p_vaddr'] <= addr and addr + size <= s['p_vaddr'] + s['p_filesz']:
                    o = s['p_offset'] + addr - s['p_vaddr']
                    return blob[o:o + size]
            return None

        relative = {}
        for sec in elf.iter_sections():
            if isinstance(sec, RelocationSection):
                for r in sec.iter_relocations():
                    if r['r_info_type'] == 8:   # R_X86_64_RELATIVE
                        relative[r['r_offset']] = r['r_addend']

        def ptr(addr):
            if addr in relative:
                return relative[addr]
            b = read(addr, 8)
            return int.from_bytes(b, 'little') if b else None

        def cstr(addr):
            b = read(addr, 256)
            return b.split(b'\0')[0].decode('latin1') if b else None

        rows = []
        for slot, typeinfo in relative.items():
            name_ptr = ptr(typeinfo + 8) if typeinfo else None
            name = cstr(name_ptr) if name_ptr else None
            # A family class: ecs::...Family... but not the abstract ecs::IFamily.
            if not name or not name.startswith('N3ecs') or 'Family' not in name or name == 'N3ecs7IFamilyE':
                continue
            vptr = slot + 8
            getter = ptr(vptr + 16)             # SysV slot 2: GetNodeList
            code = read(getter, 16) if getter else None
            if code is None:
                continue
            if code.startswith(GET_LIST):
                kind = 'list'
            elif code.startswith(GET_NONE):
                kind = 'none'
            else:
                continue
            rows.append((getter, kind, vptr, name))
    rows.sort()
    return rows


def render(rows):
    lists = [r for r in rows if r[1] == 'list']
    nones = [r for r in rows if r[1] == 'none']
    out = ['// GENERATED by tools/linux/gen_family_getters.py from the build-35924 ELF',
           '// (GNU build-id ' + BUILD_ID + '). Do not edit by hand.',
           '//',
           '// Every ECS family GetNodeList implementation (vtable slot 2). GCC keeps one',
           '// copy per family template instantiation where MSVC folds them into one, so',
           '// the native family canon must recognise each copy. Install verifies every',
           '// entry byte for byte; the canon calls none of them.',
           '#pragma once',
           '#include <cstdint>',
           '',
           '// `endbr64; lea rax,[rdi+8]; ret` -- the family holds a node list at +8.',
           'static constexpr uintptr_t kFamilyListGetters[] = {']
    for getter, _, vptr, name in lists:
        out.append('    0x%x,  // vtable 0x%x %s' % (getter, vptr, name))
    out += ['};', '',
            '// `endbr64; xor eax,eax; ret` -- the family has no node list.',
            'static constexpr uintptr_t kFamilyNoListGetters[] = {']
    for getter, _, vptr, name in nones:
        out.append('    0x%x,  // vtable 0x%x %s' % (getter, vptr, name))
    out += ['};', '',
            'static constexpr unsigned kFamilyListGetterCount = %d;' % len(lists),
            'static constexpr unsigned kFamilyNoListGetterCount = %d;' % len(nones),
            'static_assert(sizeof(kFamilyListGetters) / sizeof(kFamilyListGetters[0]) == kFamilyListGetterCount);',
            'static_assert(sizeof(kFamilyNoListGetters) / sizeof(kFamilyNoListGetters[0]) == kFamilyNoListGetterCount);',
            '']
    return '\n'.join(out)


def main():
    rows = inventory(sys.argv[1])
    lists = sum(1 for r in rows if r[1] == 'list')
    nones = sum(1 for r in rows if r[1] == 'none')
    # Windows counts the same world: 63 families, 28 node lists.
    assert (lists, nones) == (28, 35), (lists, nones)
    assert len({r[0] for r in rows}) == len(rows), 'a getter is shared: the table would be ambiguous'
    if '--header' in sys.argv:
        HEADER.write_text(render(rows), newline='\n')
        print('wrote', HEADER)
    elif '--check' in sys.argv:
        have = HEADER.read_text()
        if have != render(rows):
            print('FAIL: %s does not match the ELF inventory' % HEADER)
            sys.exit(1)
        listed = [int(x, 16) for x in re.findall(r'^\s+(0x[0-9a-f]+),', have, re.M)]
        assert len(listed) == 63
        print('PASS: family getters: %d node-list and %d no-list implementations, each a distinct function, '
              'match %s' % (lists, nones, HEADER.name))
    else:
        for getter, kind, vptr, name in rows:
            print('%#x %-4s vtable %#x %s' % (getter, kind, vptr, name))
        print('%d list, %d none' % (lists, nones))


if __name__ == '__main__':
    main()
