# Turns a binary file (the minimap button's icon) into a C++ include, so the
# plugin carries it inside the DLL like its Lua (tools/embed_lua.ps1). Called by build.bat:
#   powershell -File tools\embed_bin.ps1 -In <file> -Out <inc> -Name <symbol>
# produces `static const unsigned char <symbol>[] = { ... };` and
# `static const size_t <symbol>Size = <n>;`
param(
    [Parameter(Mandatory = $true)][string]$In,
    [Parameter(Mandatory = $true)][string]$Out,
    [Parameter(Mandatory = $true)][string]$Name
)
$ErrorActionPreference = 'Stop'
$bytes = [IO.File]::ReadAllBytes((Resolve-Path $In).Path)
$sb = New-Object System.Text.StringBuilder
[void]$sb.Append("// Generated by tools/embed_bin.ps1 from $In -- do not edit.`n")
[void]$sb.Append("static const unsigned char $($Name)[] = {`n")
for ($i = 0; $i -lt $bytes.Length; $i += 24) {
    $n = [Math]::Min(24, $bytes.Length - $i)
    $row = for ($k = 0; $k -lt $n; $k++) { '0x{0:x2}' -f $bytes[$i + $k] }
    [void]$sb.Append(($row -join ',') + ",`n")
}
[void]$sb.Append("};`n")
[void]$sb.Append("static const size_t $($Name)Size = $($bytes.Length);`n")
$new = $sb.ToString()
$old = if (Test-Path $Out) { [IO.File]::ReadAllText($Out) } else { '' }
if ($new -ne $old) { [IO.File]::WriteAllText($Out, $new, (New-Object Text.UTF8Encoding($false))) }
