# Turns a Lua file into a C++ include of raw string literal chunks, so the
# plugin carries its game script inside the DLL: one file to deploy, and the
# script can never be out of step with the native code that serves it.
# Called by build.bat:
#   powershell -File tools\embed_lua.ps1 -In <lua> -Out <inc> -Name <symbol>
# produces `static const char* const <symbol>Parts[] = { R"BMLUA(...)BMLUA", ... };`
# Chunks stay under 8 KB (MSVC caps one literal at about 16 KB).
param(
    [Parameter(Mandatory = $true)][string]$In,
    [Parameter(Mandatory = $true)][string]$Out,
    [Parameter(Mandatory = $true)][string]$Name
)
$ErrorActionPreference = 'Stop'
$text = [IO.File]::ReadAllText((Resolve-Path $In).Path) -replace "`r`n", "`n"
for ($i = 0; $i -lt $text.Length; $i++) {
    $c = [int]$text[$i]
    if ($c -gt 126 -or ($c -lt 32 -and $c -ne 10 -and $c -ne 9)) {
        throw ("{0}: character U+{1:X4} at offset {2}; the embedded script must be printable ASCII" -f $In, $c, $i)
    }
}
$delim = 'BMLUA'
if ($text.Contains(")$delim")) { throw "$In contains the raw-string delimiter )$delim" }
$chunks = New-Object System.Collections.Generic.List[string]
$cur = New-Object System.Text.StringBuilder
foreach ($line in [regex]::Split($text, '(?<=\n)')) {
    if ($line.Length -eq 0) { continue }
    if ($cur.Length -gt 0 -and $cur.Length + $line.Length -gt 8000) {
        $chunks.Add($cur.ToString())
        [void]$cur.Clear()
    }
    [void]$cur.Append($line)
}
if ($cur.Length -gt 0) { $chunks.Add($cur.ToString()) }
$sb = New-Object System.Text.StringBuilder
[void]$sb.Append("// Generated by tools/embed_lua.ps1 from $In -- do not edit.`n")
[void]$sb.Append("static const char* const $($Name)Parts[] = {`n")
foreach ($chunk in $chunks) { [void]$sb.Append('R"' + $delim + '(' + $chunk + ')' + $delim + '",' + "`n") }
[void]$sb.Append("};`n")
$new = $sb.ToString()
$old = if (Test-Path $Out) { [IO.File]::ReadAllText($Out) } else { '' }
if ($new -ne $old) { [IO.File]::WriteAllText($Out, $new, (New-Object Text.UTF8Encoding($false))) }
