// Terrain buffer reuse for mod terrain generators, without a mod and without
// touching the other mod's files.
//
// The native toolkit keeps one full-map float buffer per distinct buffer name
// until the pipeline ends (docs/generation-peak.md). The Fantasia Map
// Generator (workshop 2916150031) uses 224 names at 32 x 32 km and 325 at
// 40 km -- MEASURED 53-63 live maps and a std::bad_alloc at 40 km -- and
// mod/generation/bigmap_memory.lua brings every one of its pipelines down to
// 10, the lower bound (tools/test_generator_memory.py).
//
// How: the exe's imports that open files (CreateFileW, _wfopen, fopen and
// std::_Fiopen) are pointed at detours. A read-only open of one of the
// generator files in GENERATORS, in any mod's res\config\terrain_generators, is
// served from a patched copy in %TEMP%\tpf2_bigmap: the one line
// "\t\treturn result" of its updateFn becomes
//     return _tpf2_bigmap_generate(result, params)
// and the pass itself (embedded from bigmap_memory.lua) plus that helper are
// appended after the last line, so every line number in the generator stays
// the same. The helper prints the map size, layer and name counts to the game
// log and runs the pass when the map is over 8193^2 heightmap samples. Maps up to
// 32 x 32 km (128 x 128 tiles) run the generator exactly as shipped. A file
// whose anchor is missing or repeated is served unchanged. The generator on
// disk is never written; switching the plugin off (generator_memory=0) or
// removing it restores stock behaviour on the next start.
//
// Needs ReadWholeFile / WriteWholeFile from bigmap.cpp. Both builds: the
// import slots are found by walking the exe's import directory.
#pragma once
#include "../out/generator_memory_lua.inc"   // kGeneratorMemoryLuaParts[], generated by build.bat

static bool g_generatorMemory = true;
static int g_generatorBudgetPct = 50;   // generator_memory_budget_pct: share of free memory for extra buffers

// The generation's buffer budget: generator_memory_budget_pct of the memory
// free when the generator file is opened -- the smaller of free physical
// memory and commit headroom, as a machine without a page file fails its
// allocations on commit. 0 = the fewest buffers.
static unsigned long long GeneratorBudgetBytes() {
    if (g_generatorBudgetPct <= 0) return 0;
    MEMORYSTATUSEX m = {sizeof m};
    if (!GlobalMemoryStatusEx(&m)) return 0;
    unsigned long long avail = m.ullAvailPhys < m.ullAvailPageFile ? m.ullAvailPhys : m.ullAvailPageFile;
    return avail / 100 * (unsigned long long)(g_generatorBudgetPct > 90 ? 90 : g_generatorBudgetPct);
}

static const wchar_t* const kGeneratorFiles[] = {
    L"fantasia_map_generator.gen.lua",
    L"fantasia_map_generator_dry.gen.lua",
    L"fantasia_map_generator_tropical.gen.lua",
};
// Index into kGeneratorFiles when `path` is <...>\res\config\terrain_generators\<file>, else -1.
static int GeneratorFileIndex(const wchar_t* path) {
    if (!path) return -1;
    wchar_t low[MAX_PATH * 2];
    size_t n = 0;
    for (; path[n] && n + 1 < _countof(low); ++n) {
        wchar_t c = path[n] == L'/' ? L'\\' : path[n];
        low[n] = (c >= L'A' && c <= L'Z') ? wchar_t(c - L'A' + L'a') : c;
    }
    if (path[n]) return -1;
    low[n] = 0;
    static const wchar_t dir[] = L"\\res\\config\\terrain_generators\\";
    for (int i = 0; i < (int)_countof(kGeneratorFiles); ++i) {
        size_t f = wcslen(kGeneratorFiles[i]), d = _countof(dir) - 1;
        if (n < f + d) continue;
        if (wcscmp(low + n - f, kGeneratorFiles[i]) == 0 && wcsncmp(low + n - f - d, dir, d) == 0) return i;
    }
    return -1;
}

#include "generator_memory_text.h"

static SRWLOCK g_genLock = SRWLOCK_INIT;
static volatile LONG g_genServed[_countof(kGeneratorFiles)];

// The copy carries the original's creation and write times. The game checks
// whether a generator changed through both its path and an open handle; a copy
// with its own times (written at every start) read as a generator that changed
// at every check, and the New Game preview threw its map away and generated it
// again, endlessly, on every generator and size (2026-09-27, 0.7.0.7 and 0.7.1).
static void GeneratorCopyTimes(const wchar_t* from, const wchar_t* to) {
    WIN32_FILE_ATTRIBUTE_DATA a;
    if (!GetFileAttributesExW(from, GetFileExInfoStandard, &a)) return;
    HANDLE h = CreateFileW(to, FILE_WRITE_ATTRIBUTES, FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE,
                           nullptr, OPEN_EXISTING, 0, nullptr);   // the plugin's own import, not the exe's
    if (h == INVALID_HANDLE_VALUE) return;
    SetFileTime(h, &a.ftCreationTime, nullptr, &a.ftLastWriteTime);
    CloseHandle(h);
}

// The patched copy of `path` in %TEMP%\tpf2_bigmap, written when it differs, with
// the original's times. False (serve the original) on any failure.
static bool GeneratorRedirect(const wchar_t* path, wchar_t* out, size_t cch) {
    int i = GeneratorFileIndex(path);
    if (i < 0 || !g_generatorMemory) return false;
    wchar_t dir[MAX_PATH];
    DWORD t = GetTempPathW(MAX_PATH, dir);
    if (!t || t >= MAX_PATH) return false;
    if (_snwprintf_s(out, cch, _TRUNCATE, L"%stpf2_bigmap", dir) < 0) return false;
    CreateDirectoryW(out, nullptr);
    if (_snwprintf_s(out, cch, _TRUNCATE, L"%stpf2_bigmap\\%s", dir, kGeneratorFiles[i]) < 0) return false;

    AcquireSRWLockExclusive(&g_genLock);
    bool ok = false;
    char *src = nullptr, *cur = nullptr, *patched = nullptr;
    size_t srcLen = 0, curLen = 0, patchedLen = 0;
    if (ReadWholeFile(path, &src, &srcLen) && (patched = PatchGeneratorText(src, srcLen, &patchedLen, GeneratorBudgetBytes()))) {
        bool same = ReadWholeFile(out, &cur, &curLen) && curLen == patchedLen && memcmp(cur, patched, curLen) == 0;
        ok = same || WriteWholeFile(out, patched, patchedLen);
        if (ok) GeneratorCopyTimes(path, out);
    }
    ReleaseSRWLockExclusive(&g_genLock);
    if (H && InterlockedExchange(&g_genServed[i], 1) == 0) {
        if (ok) H->log("generator memory: %ls served with buffer reuse above 32 x 32 km (%ls)", kGeneratorFiles[i], out);
        else H->log("generator memory: %ls served unchanged (%s)", kGeneratorFiles[i],
                    src ? "its 'return result' line is missing or repeated" : "unreadable");
    }
    free(src); free(cur); free(patched);
    return ok;
}

// ---- import detours --------------------------------------------------------
using CreateFileWFn = HANDLE(WINAPI*)(LPCWSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE);
using WfopenFn = FILE*(__cdecl*)(const wchar_t*, const wchar_t*);
using FopenFn = FILE*(__cdecl*)(const char*, const char*);
using FiopenFn = FILE*(__cdecl*)(const wchar_t*, int, int);
static CreateFileWFn g_origCreateFileW;
static WfopenFn g_origWfopen;
static FopenFn g_origFopen;
static FiopenFn g_origFiopen;

// Only an open that reads the file's bytes is served the copy: one that asks only
// for its attributes or times sees the original, as every path-based query does.
static HANDLE WINAPI GenCreateFileW(LPCWSTR path, DWORD access, DWORD share, LPSECURITY_ATTRIBUTES sa,
                                    DWORD disposition, DWORD flags, HANDLE tmpl) {
    wchar_t alt[MAX_PATH];
    if ((access & (GENERIC_READ | FILE_READ_DATA)) &&
        !(access & (GENERIC_WRITE | GENERIC_ALL | FILE_WRITE_DATA | FILE_APPEND_DATA | DELETE)) &&
        disposition == OPEN_EXISTING && GeneratorRedirect(path, alt, MAX_PATH))
        path = alt;
    return g_origCreateFileW(path, access, share, sa, disposition, flags, tmpl);
}
static bool ReadOnlyMode(const wchar_t* m) { return m && !wcspbrk(m, L"wa+"); }
static FILE* __cdecl GenWfopen(const wchar_t* path, const wchar_t* mode) {
    wchar_t alt[MAX_PATH];
    if (ReadOnlyMode(mode) && GeneratorRedirect(path, alt, MAX_PATH)) path = alt;
    return g_origWfopen(path, mode);
}
static FILE* __cdecl GenFopen(const char* path, const char* mode) {
    if (path && mode && !strpbrk(mode, "wa+")) {
        // The narrow path is UTF-8 or the ANSI code page; answer in the one that decoded it.
        const UINT pages[] = {CP_UTF8, CP_ACP};
        for (UINT cp : pages) {
            wchar_t wide[MAX_PATH], alt[MAX_PATH];
            if (!MultiByteToWideChar(cp, cp == CP_UTF8 ? MB_ERR_INVALID_CHARS : 0, path, -1, wide, MAX_PATH)) continue;
            if (GeneratorFileIndex(wide) < 0) return g_origFopen(path, mode);
            char narrow[MAX_PATH * 3];
            BOOL lossy = FALSE;
            if (GeneratorRedirect(wide, alt, MAX_PATH) &&
                WideCharToMultiByte(cp, 0, alt, -1, narrow, sizeof narrow, nullptr, cp == CP_UTF8 ? nullptr : &lossy) && !lossy)
                return g_origFopen(narrow, mode);
            break;
        }
    }
    return g_origFopen(path, mode);
}
static FILE* __cdecl GenFiopen(const wchar_t* path, int mode, int prot) {
    // std::ios_base: out 0x02, app 0x08, trunc 0x10.
    wchar_t alt[MAX_PATH];
    if (!(mode & (0x02 | 0x08 | 0x10)) && GeneratorRedirect(path, alt, MAX_PATH)) path = alt;
    return g_origFiopen(path, mode, prot);
}

// RVA of the import slot for dll!name in the exe, 0 when it is not imported by name.
static uintptr_t ImportSlotRva(uintptr_t base, const char* dll, const char* name) {
    auto dos = reinterpret_cast<const IMAGE_DOS_HEADER*>(base);
    auto nt = reinterpret_cast<const IMAGE_NT_HEADERS64*>(base + dos->e_lfanew);
    const IMAGE_DATA_DIRECTORY& dirEntry = nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT];
    if (!dirEntry.VirtualAddress) return 0;
    for (auto d = reinterpret_cast<const IMAGE_IMPORT_DESCRIPTOR*>(base + dirEntry.VirtualAddress); d->Name; ++d) {
        if (_stricmp(reinterpret_cast<const char*>(base + d->Name), dll) != 0 || !d->OriginalFirstThunk) continue;
        auto names = reinterpret_cast<const IMAGE_THUNK_DATA64*>(base + d->OriginalFirstThunk);
        for (size_t k = 0; names[k].u1.AddressOfData; ++k) {
            if (IMAGE_SNAP_BY_ORDINAL64(names[k].u1.Ordinal)) continue;
            auto byName = reinterpret_cast<const IMAGE_IMPORT_BY_NAME*>(base + names[k].u1.AddressOfData);
            if (strcmp(reinterpret_cast<const char*>(byName->Name), name) == 0)
                return d->FirstThunk + k * sizeof(IMAGE_THUNK_DATA64);
        }
    }
    return 0;
}

static bool RouteImport(const char* dll, const char* name, void* detour, void** original) {
    uintptr_t base = H->moduleBase();
    uintptr_t rva = ImportSlotRva(base, dll, name);
    if (!rva) { H->log("generator memory: %s!%s is not imported; that open path is not watched", dll, name); return false; }
    *original = *reinterpret_cast<void**>(base + rva);
    uint8_t bytes[8]; memcpy(bytes, &detour, 8);
    if (!H->patchBytes(rva, bytes, 8)) { H->log("generator memory: %s!%s import patch failed", dll, name); return false; }
    return true;
}

static bool InstallGeneratorMemory() {
    if (!g_generatorMemory) { H->log("generator memory: off (generator_memory=0)"); return false; }
    int routed = 0;
    routed += RouteImport("KERNEL32.dll", "CreateFileW", (void*)GenCreateFileW, (void**)&g_origCreateFileW);
    routed += RouteImport("api-ms-win-crt-stdio-l1-1-0.dll", "_wfopen", (void*)GenWfopen, (void**)&g_origWfopen);
    routed += RouteImport("api-ms-win-crt-stdio-l1-1-0.dll", "fopen", (void*)GenFopen, (void**)&g_origFopen);
    routed += RouteImport("MSVCP140.dll", "?_Fiopen@std@@YAPEAU_iobuf@@PEB_WHH@Z", (void*)GenFiopen, (void**)&g_origFiopen);
    if (!routed) { H->log("generator memory: no file-open import could be watched; OFF"); return false; }
    H->log("generator memory: Fantasia Map Generator files get buffer reuse above 32 x 32 km (%d of 4 open paths watched; the files on disk are not changed)", routed);
    return true;
}

extern "C" __declspec(dllexport) int BigmapTestGeneratorRedirect(const wchar_t* path, wchar_t* out, size_t cch) { return GeneratorRedirect(path, out, cch); }
extern "C" __declspec(dllexport) int BigmapTestGeneratorIndex(const wchar_t* path) { return GeneratorFileIndex(path); }
extern "C" __declspec(dllexport) long long BigmapTestGeneratorPatch(const char* src, size_t len, char* out, size_t cap, unsigned long long budget) {
    size_t n = 0;
    char* p = PatchGeneratorText(src, len, &n, budget);
    if (!p) return -1;
    long long r = (long long)n;
    if (n <= cap) memcpy(out, p, n);
    free(p);
    return r;
}
