// Steam 35924: an in-game minimap that works on the largest maps.
//
// The picture is not drawn by Lua. The minimap game script
// (mod/minimap/bigmap_minimap.lua, written into res/config/game_script at
// start) calls an ordinary ImageView's setImage() with a token
//
//   bigmap:minimap?x0=<m>&y0=<m>&x1=<m>&y1=<m>&w=<px>&h=<px>[&relief=<k>][&g=<n>]
//
// and the detour on ImageView::SetImage(string) (0x22b4610, the only image
// method Lua can reach) renders that world rectangle from the live terrain and
// uploads it as the image's texture through ImageView::SetImage(raw)
// (0x22b4350), the path the engine's own map preview uses. There is no widget
// per pixel and no line primitive, so the cost is the pixel count, not the map
// size. Every other image path passes straight through after a prefix check.
//
// Heights come from CTerrain::BaseGetVertices (0x33d130), the 65x65 base
// heightmap per tile, which the height-cache pager never touches. The terrain
// is reached the way the UI reaches it: *(CGameUI+0x450) -> vtbl[1] -> +0x20.
// CGameUI is captured by a thunk on CreateConstructionMenu (0x5a2900), which
// runs once per world. Colouring follows the engine's CreateTextureData
// (0x63b9a0): the default climate height ramp, a water depth ramp, a hillshade
// and a 24-direction ambient term.
//
// Reverse engineering: docs/minimap-native-preview.md. Included after H,
// g_gog, ReadWholeFile and WriteWholeFile. Steam only.
#pragma once
#include <functional>
#include <limits>
#include <thread>
#include <vector>
#include "../out/minimap_lua.inc"   // kMinimapLuaParts[], generated by build.bat

static bool g_minimap = false;

// ---- game ABI -------------------------------------------------------------
// MSVC x64 release std::string: 16-byte SSO buffer or heap pointer, then size
// and capacity. Data lives in the buffer while capacity <= 15.
struct MinimapMsvcString {
    union { char buf[16]; char* ptr; };
    uint64_t size, cap;
};
static char* MinimapStringData(MinimapMsvcString* s) { return s->cap > 15 ? s->ptr : s->buf; }

using MinimapSetImagePathFn = void* (__fastcall*)(void* imageView, MinimapMsvcString* path, uint64_t flag);
using MinimapSetImageRawFn = void* (__fastcall*)(void* imageView, int channels, int w, int h,
                                                  const void* pixels /* const vector<uint8>& */, uint64_t validate);
// const vector<uint16>& BaseGetVertices(CVec2i tile): the tile arrives packed in
// rdx, x in the low 32 bits and y in the high 32 (0x33d13a..0x33d150).
using MinimapVerticesFn = const void* (__fastcall*)(void* terrain, uint64_t tile);

static MinimapSetImagePathFn g_minimapSetImagePath = nullptr;   // trampoline
static MinimapSetImageRawFn g_minimapSetImageRaw = nullptr;
static MinimapVerticesFn g_minimapBaseGetVertices = nullptr;
static void* g_minimapGameUI = nullptr;                // written by the capture thunk
static void* g_minimapCreateMenuTrampoline = nullptr;
static uintptr_t g_minimapImageLo = 0, g_minimapImageHi = 0;

// ---- request token --------------------------------------------------------
// One header line, optionally followed by "\n" and a network payload:
//
//   bigmap:minimap?x0=&y0=&x1=&y1=&w=&h=[&relief=][&g=][&layers=][&net=][&hide=]
//   P <index> <r> <g> <b>                              palette entry (owner colour)
//   E <class> <colour> x0 y0 tx0 ty0 x1 y1 tx1 ty1     edge, Hermite tangents in metres
//   S <class> <colour> x y ux uy half                  station: centre, direction x1000, half length
//
// layers: 1 roads, 2 tracks, 4 stations. net: the id of the network to draw; a
// payload replaces the cached network under that id, and a header-only request
// draws the cache only if its id matches, so a previous world's network never
// shows. hide: bit mask of palette indices (companies) not to draw.
static const char kMinimapToken[] = "bigmap:minimap";
enum { MINIMAP_TOKEN_LEN = 14, MINIMAP_MIN_PX = 16, MINIMAP_MAX_PX = 4096, MINIMAP_HEADER_MAX = 1024 };
enum { MINIMAP_LAYER_ROADS = 1, MINIMAP_LAYER_TRACKS = 2, MINIMAP_LAYER_STATIONS = 4 };
enum { MINIMAP_EDGE_URBAN = 0, MINIMAP_EDGE_COUNTRY = 1, MINIMAP_EDGE_HIGHWAY = 2, MINIMAP_EDGE_TRACK = 3 };
enum { MINIMAP_MAX_PALETTE = 53 };   // hide is a double-exact integer mask

struct MinimapRequest {
    double x0, y0, x1, y1, relief;
    int w, h;
    int layers;
    uint64_t net, hide;
};

static bool MinimapIsToken(const char* text, uint64_t len) {
    return len >= MINIMAP_TOKEN_LEN && memcmp(text, kMinimapToken, MINIMAP_TOKEN_LEN) == 0;
}

// Length of the header line (up to the first newline).
static size_t MinimapHeaderLength(const char* text, size_t len) {
    const void* nl = memchr(text, '\n', len);
    return nl ? size_t(static_cast<const char*>(nl) - text) : len;
}

// Strict: every key known, every value a complete finite number, the rectangle
// non-empty and bounded, the size whole and within [16, 4096]. Parses the
// header line only; a payload after it is MinimapParseNetwork's.
static bool MinimapParse(const char* text, size_t len, MinimapRequest* r) {
    char buf[MINIMAP_HEADER_MAX];
    len = MinimapHeaderLength(text, len);
    if (!MinimapIsToken(text, len) || len >= sizeof buf) return false;
    memcpy(buf, text, len);
    buf[len] = 0;
    char* p = buf + MINIMAP_TOKEN_LEN;
    if (*p++ != '?') return false;
    MinimapRequest q{};
    q.relief = 4.0;
    unsigned seen = 0;
    for (;;) {
        char* amp = strchr(p, '&');
        if (amp) *amp = 0;
        char* eq = strchr(p, '=');
        if (!eq || eq == p) return false;
        *eq = 0;
        const char* val = eq + 1;
        char* end = nullptr;
        const double v = strtod(val, &end);
        if (end == val || *end != 0 || !std::isfinite(v)) return false;
        if      (!strcmp(p, "x0")) { q.x0 = v; seen |= 1; }
        else if (!strcmp(p, "y0")) { q.y0 = v; seen |= 2; }
        else if (!strcmp(p, "x1")) { q.x1 = v; seen |= 4; }
        else if (!strcmp(p, "y1")) { q.y1 = v; seen |= 8; }
        else if (!strcmp(p, "w"))  { if (v != std::floor(v)) return false; q.w = int(v < 0 ? -1 : v > 1e6 ? 1e6 : v); seen |= 16; }
        else if (!strcmp(p, "h"))  { if (v != std::floor(v)) return false; q.h = int(v < 0 ? -1 : v > 1e6 ? 1e6 : v); seen |= 32; }
        else if (!strcmp(p, "relief")) { if (v < 0 || v > 64) return false; q.relief = v; }
        else if (!strcmp(p, "g")) {}    // generation counter: makes each request a new string
        else if (!strcmp(p, "layers")) { if (v < 0 || v > 7 || v != std::floor(v)) return false; q.layers = int(v); }
        else if (!strcmp(p, "net")) { if (v < 0 || v > 9007199254740992.0 || v != std::floor(v)) return false; q.net = uint64_t(v); }
        else if (!strcmp(p, "hide")) { if (v < 0 || v > 9007199254740991.0 || v != std::floor(v)) return false; q.hide = uint64_t(v); }
        else return false;
        if (!amp) break;
        p = amp + 1;
    }
    if (seen != 63) return false;
    const double lim = 1e7;
    if (!(q.x1 > q.x0 && q.y1 > q.y0 && std::fabs(q.x0) <= lim && std::fabs(q.x1) <= lim &&
          std::fabs(q.y0) <= lim && std::fabs(q.y1) <= lim)) return false;
    if (q.w < MINIMAP_MIN_PX || q.h < MINIMAP_MIN_PX || q.w > MINIMAP_MAX_PX || q.h > MINIMAP_MAX_PX) return false;
    *r = q;
    return true;
}

// ---- network payload ----------------------------------------------------------
struct MinimapNetEdge { float x0, y0, tx0, ty0, x1, y1, tx1, ty1; uint8_t cls; int8_t colour; };
struct MinimapNetStation { float x, y, ux, uy, half; uint8_t cls; int8_t colour; };
struct MinimapNet {
    uint64_t id = 0;
    std::vector<MinimapNetEdge> edges;
    std::vector<MinimapNetStation> stations;
    uint32_t palette[MINIMAP_MAX_PALETTE] = {};
    bool paletteSet[MINIMAP_MAX_PALETTE] = {};
    size_t rejected = 0;
};
static MinimapNet g_minimapNet;
static SRWLOCK g_minimapNetLock = SRWLOCK_INIT;

// Reads whitespace-separated numbers from one line; false on anything else.
static bool MinimapReadNumbers(const char*& p, const char* end, double* out, int count) {
    for (int i = 0; i < count; ++i) {
        while (p < end && (*p == ' ' || *p == '\t')) ++p;
        if (p >= end) return false;
        char tmp[48];
        size_t n = 0;
        while (p < end && *p != ' ' && *p != '\t' && *p != '\r' && n < sizeof tmp - 1) tmp[n++] = *p++;
        if (n == 0 || n == sizeof tmp - 1) return false;
        tmp[n] = 0;
        char* stop = nullptr;
        out[i] = strtod(tmp, &stop);
        if (*stop != 0 || !std::isfinite(out[i])) return false;
    }
    while (p < end && (*p == ' ' || *p == '\t' || *p == '\r')) ++p;
    return p == end;
}

// Parses the lines after the header into `net`. Malformed lines are counted
// and skipped; limits keep a hostile string from exhausting memory.
static void MinimapParseNetwork(const char* p, const char* end, MinimapNet* net) {
    const double lim = 1e7;
    while (p < end) {
        const char* nl = static_cast<const char*>(memchr(p, '\n', size_t(end - p)));
        const char* lineEnd = nl ? nl : end;
        const char kind = *p;
        const char* q = p + 1;
        double v[10];
        bool ok = false;
        if (kind == 'P' && MinimapReadNumbers(q, lineEnd, v, 4)) {
            const int idx = int(v[0]);
            if (v[0] == idx && idx >= 0 && idx < MINIMAP_MAX_PALETTE && v[1] >= 0 && v[1] <= 255 &&
                v[2] >= 0 && v[2] <= 255 && v[3] >= 0 && v[3] <= 255) {
                net->palette[idx] = (uint32_t(v[1]) << 16) | (uint32_t(v[2]) << 8) | uint32_t(v[3]);
                net->paletteSet[idx] = true;
                ok = true;
            }
        } else if (kind == 'E' && MinimapReadNumbers(q, lineEnd, v, 10)) {
            bool inRange = v[0] >= 0 && v[0] <= 3 && v[0] == std::floor(v[0]) &&
                           v[1] >= -1 && v[1] < MINIMAP_MAX_PALETTE && v[1] == std::floor(v[1]);
            for (int i = 2; i < 10; ++i) inRange = inRange && std::fabs(v[i]) <= lim;
            if (inRange && net->edges.size() < 8000000) {
                net->edges.push_back({ float(v[2]), float(v[3]), float(v[4]), float(v[5]), float(v[6]), float(v[7]),
                                       float(v[8]), float(v[9]), uint8_t(v[0]), int8_t(v[1]) });
                ok = true;
            }
        } else if (kind == 'S' && MinimapReadNumbers(q, lineEnd, v, 7)) {
            bool inRange = v[0] >= 0 && v[0] <= 3 && v[0] == std::floor(v[0]) &&
                           v[1] >= -1 && v[1] < MINIMAP_MAX_PALETTE && v[1] == std::floor(v[1]) &&
                           v[6] >= 0 && v[6] <= 5000;
            for (int i = 2; i < 6; ++i) inRange = inRange && std::fabs(v[i]) <= lim;
            if (inRange && net->stations.size() < 1000000) {
                const double len = std::sqrt(v[4] * v[4] + v[5] * v[5]);
                net->stations.push_back({ float(v[2]), float(v[3]), float(len > 0 ? v[4] / len : 1.0),
                                          float(len > 0 ? v[5] / len : 0.0), float(v[6]), uint8_t(v[0]), int8_t(v[1]) });
                ok = true;
            }
        } else if (lineEnd == p || (lineEnd == p + 1 && *p == '\r')) {
            ok = true;   // blank line
        }
        if (!ok) ++net->rejected;
        p = nl ? nl + 1 : end;
    }
}

// ---- terrain --------------------------------------------------------------
struct MinimapTerrain {
    void* self;
    const uint8_t* cells;        // 0x28-byte cells, tile entity id at +0 (-1 = none)
    int x0, y0, w, h, perTile;   // tile rectangle and base samples per tile edge
    float resX, resY, zScale, zOffset, water;
};

// Offsets pinned by the byte-verified getters: levels +0x28 (0x33d270),
// resolution +0x2c/+0x30/+0x34 (0x33d280), height offset +0x3c (0x33d560),
// water level +0x40 (0x33d7f0), tile grid header at *(+0x18) (0x33d540).
static bool MinimapReadTerrain(void* t, MinimapTerrain* m) {
    if (!t) return false;
    const uint8_t* self = static_cast<const uint8_t*>(t);
    const uint8_t* hdr = nullptr;
    memcpy(&hdr, self + 0x18, sizeof hdr);
    if (!hdr) return false;
    int levels = 0;
    memcpy(&levels, self + 0x28, 4);
    memcpy(&m->x0, hdr + 0x00, 4);
    memcpy(&m->y0, hdr + 0x04, 4);
    memcpy(&m->w, hdr + 0x08, 4);
    memcpy(&m->h, hdr + 0x0c, 4);
    memcpy(&m->cells, hdr + 0x10, sizeof m->cells);
    memcpy(&m->resX, self + 0x2c, 4);
    memcpy(&m->resY, self + 0x30, 4);
    memcpy(&m->zScale, self + 0x34, 4);
    memcpy(&m->zOffset, self + 0x3c, 4);
    memcpy(&m->water, self + 0x40, 4);
    if (levels < 1 || levels > 10 || m->w < 1 || m->h < 1 || m->w > 16384 || m->h > 16384 || !m->cells) return false;
    if (!(m->resX > 0 && m->resY > 0 && std::isfinite(m->resX) && std::isfinite(m->resY) &&
          std::isfinite(m->zScale) && std::isfinite(m->zOffset) && std::isfinite(m->water))) return false;
    m->perTile = 1 << levels;
    m->self = t;
    return true;
}

// Heights in metres at pixel centres; NaN outside the tile rectangle or on a
// missing tile. Row 0 is the SOUTH edge (minimum world y): ImageView draws
// texture row 0 at the bottom (0x22b3860), like the engine's preview.
static void MinimapSampleHeights(const MinimapTerrain& m, const MinimapRequest& r, float* out) {
    const double tileW = double(m.perTile) * m.resX, tileH = double(m.perTile) * m.resY;
    // The engine's own origin for this grid (MapPreviewComp markers, 0x5c9a90):
    // (-(W/2) tiles, -(H/2) tiles), integer halves; tile (x0, y0) starts there.
    const double originX = -double(m.w / 2) * tileW, originY = -double(m.h / 2) * tileH;
    const int side = m.perTile + 1;
    const double stepX = (r.x1 - r.x0) / r.w, stepY = (r.y1 - r.y0) / r.h;
    uint64_t cachedKey = ~uint64_t(0);
    const uint16_t* cached = nullptr;
    for (int py = 0; py < r.h; ++py) {
        const double fy = (r.y0 + (py + 0.5) * stepY - originY) / tileH;
        const double ryf = std::floor(fy);
        for (int px = 0; px < r.w; ++px) {
            float& o = out[size_t(py) * size_t(r.w) + size_t(px)];
            o = std::numeric_limits<float>::quiet_NaN();
            const double fx = (r.x0 + (px + 0.5) * stepX - originX) / tileW;
            const double rxf = std::floor(fx);
            if (rxf < 0 || ryf < 0 || rxf >= m.w || ryf >= m.h) continue;
            const int rx = int(rxf), ry = int(ryf);
            const uint64_t key = (uint64_t(uint32_t(ry)) << 32) | uint32_t(rx);
            if (key != cachedKey) {
                cachedKey = key;
                cached = nullptr;
                int entity = -1;
                memcpy(&entity, m.cells + (size_t(ry) * size_t(m.w) + size_t(rx)) * 0x28, 4);
                // BaseGetVertices asserts on an empty cell (0x33d166), so check first.
                if (entity != -1 && g_minimapBaseGetVertices) {
                    const uint32_t tx = uint32_t(m.x0 + rx), ty = uint32_t(m.y0 + ry);
                    const void* vec = g_minimapBaseGetVertices(m.self, uint64_t(tx) | (uint64_t(ty) << 32));
                    if (vec) {
                        const uint16_t* b = nullptr;
                        const uint16_t* e = nullptr;
                        memcpy(&b, vec, sizeof b);
                        memcpy(&e, static_cast<const uint8_t*>(vec) + 8, sizeof e);
                        if (b && e > b && size_t(e - b) >= size_t(side) * size_t(side)) cached = b;
                    }
                }
            }
            if (!cached) continue;
            int ix = int((fx - rxf) * m.perTile + 0.5), iy = int((fy - ryf) * m.perTile + 0.5);
            if (ix > m.perTile) ix = m.perTile;
            if (iy > m.perTile) iy = m.perTile;
            o = float(cached[size_t(iy) * size_t(side) + size_t(ix)]) * m.zScale + m.zOffset;
        }
    }
}

// ---- colouring ------------------------------------------------------------
struct MinimapRgb { float r, g, b; };
static MinimapRgb MinimapLerp(const MinimapRgb& a, const MinimapRgb& b, float t) {
    return { a.r + (b.r - a.r) * t, a.g + (b.g - a.g) * t, a.b + (b.b - a.b) * t };
}
static MinimapRgb MinimapColour(int r, int g, int b) { return { r / 255.0f, g / 255.0f, b / 255.0f }; }

// The engine's default PreviewColoring (0x36d810), which temperate uses.
static MinimapRgb MinimapRamp(float h) {
    static const float heights[3] = { 0.0f, 100.0f, 550.0f };
    static const MinimapRgb colours[3] = { MinimapColour(93, 112, 66), MinimapColour(64, 78, 50),
                                           MinimapColour(242, 235, 220) };
    if (!(h > heights[0])) return colours[0];
    if (h >= heights[2]) return colours[2];
    const int i = h < heights[1] ? 0 : 1;
    return MinimapLerp(colours[i], colours[i + 1], (h - heights[i]) / (heights[i + 1] - heights[i]));
}

static uint8_t MinimapByte(float v) {
    return uint8_t(v <= 0 ? 0 : v >= 1 ? 255 : int(v * 255.0f + 0.5f));
}

static void MinimapShadeRows(const MinimapTerrain& m, const MinimapRequest& r, const float* hts,
                             uint8_t* rgba, int row0, int row1) {
    static const MinimapRgb water0 = MinimapColour(100, 135, 158), water1 = MinimapColour(60, 80, 91);
    static const MinimapRgb ambientC = MinimapColour(204, 230, 255), sunC = MinimapColour(255, 255, 204);
    static const MinimapRgb outside = MinimapColour(26, 28, 32);
    // 24 hemisphere directions: 3 rings at theta = (i+0.5)/3 * pi/2 from the
    // zenith, 8 azimuths each (as 0x63aa90).
    double dirs[24][3];
    double dirZ = 0;
    for (int i = 0; i < 3; ++i)
        for (int k = 0; k < 8; ++k) {
            const double th = (i + 0.5) / 3.0 * 1.5707963267948966, ph = k * 0.7853981633974483;
            double* d = dirs[i * 8 + k];
            d[0] = std::sin(th) * std::cos(ph);
            d[1] = std::sin(th) * std::sin(ph);
            d[2] = std::cos(th);
            dirZ += d[2];
        }
    const double stepX = (r.x1 - r.x0) / r.w, stepY = (r.y1 - r.y0) / r.h;
    const auto at = [&](int x, int y, float fallback) {
        if (x < 0 || y < 0 || x >= r.w || y >= r.h) return fallback;
        const float v = hts[size_t(y) * size_t(r.w) + size_t(x)];
        return v == v ? v : fallback;
    };
    for (int y = row0; y < row1; ++y) {
        for (int x = 0; x < r.w; ++x) {
            const float h = hts[size_t(y) * size_t(r.w) + size_t(x)];
            MinimapRgb c;
            if (!(h == h)) {
                c = outside;
            } else if (h < m.water) {
                float t = (h - m.water) / (-100.0f - m.water);
                t = t < 0 ? 0 : t > 1 ? 1 : t;
                c = MinimapLerp(water0, water1, t);
            } else {
                const double gx = (double(at(x + 1, y, h)) - at(x - 1, y, h)) / (2 * stepX) * r.relief;
                const double gy = (double(at(x, y + 1, h)) - at(x, y - 1, h)) / (2 * stepY) * r.relief;
                const double len = std::sqrt(gx * gx + gy * gy + 1);
                const double nx = -gx / len, ny = -gy / len, nz = 1 / len;
                const double sun = (std::max)(0.0, (-nx + ny + nz) / std::sqrt(3.0));
                double amb = 3 * nz;
                for (int i = 0; i < 24; ++i)
                    amb += (std::max)(0.0, nx * dirs[i][0] + ny * dirs[i][1] + nz * dirs[i][2]);
                amb /= 3 + dirZ;
                const MinimapRgb base = MinimapRamp(h);
                c = { float(base.r * (amb * ambientC.r + sun * sunC.r) * 0.5),
                      float(base.g * (amb * ambientC.g + sun * sunC.g) * 0.5),
                      float(base.b * (amb * ambientC.b + sun * sunC.b) * 0.5) };
            }
            uint8_t* p = rgba + (size_t(y) * size_t(r.w) + size_t(x)) * 4;
            p[0] = MinimapByte(c.r);
            p[1] = MinimapByte(c.g);
            p[2] = MinimapByte(c.b);
            p[3] = 255;
        }
    }
}

// Shading touches only the height buffer, so it can use every core.
static void MinimapShade(const MinimapTerrain& m, const MinimapRequest& r, const float* hts, uint8_t* rgba) {
    unsigned n = std::thread::hardware_concurrency();
    if (n < 1) n = 1;
    if (n > 8) n = 8;
    if (unsigned(r.h) < n * 16) n = 1;
    std::thread workers[8];
    unsigned started = 0;
    for (unsigned i = 1; i < n; ++i) {
        try {
            workers[started] = std::thread(MinimapShadeRows, std::cref(m), std::cref(r), hts, rgba,
                                           int(r.h * i / n), int(r.h * (i + 1) / n));
            ++started;
        } catch (...) {
            MinimapShadeRows(m, r, hts, rgba, int(r.h * i / n), int(r.h * (i + 1) / n));
        }
    }
    MinimapShadeRows(m, r, hts, rgba, 0, int(r.h / n));
    for (unsigned i = 0; i < started; ++i) workers[i].join();
}

// ---- network overlay ------------------------------------------------------
static int MinimapClampInt(double v, int lo, int hi) {
    return v < lo ? lo : v > hi ? hi : int(v);
}

// Anti-aliased thick segment in texture space (x across, y = texture row, row 0
// south), blended over what is already there.
static void MinimapStroke(uint8_t* rgba, int w, int h, double ax, double ay, double bx, double by,
                          double r, uint32_t rgb, double alpha) {
    const double ext = r + 1.0;
    const int xmin = MinimapClampInt(std::floor((std::min)(ax, bx) - ext), 0, w);
    const int xmax = MinimapClampInt(std::ceil((std::max)(ax, bx) + ext), -1, w - 1);
    const int ymin = MinimapClampInt(std::floor((std::min)(ay, by) - ext), 0, h);
    const int ymax = MinimapClampInt(std::ceil((std::max)(ay, by) + ext), -1, h - 1);
    if (xmin > xmax || ymin > ymax) return;
    const double dx = bx - ax, dy = by - ay, len2 = dx * dx + dy * dy;
    const double cr = (rgb >> 16) & 255, cg = (rgb >> 8) & 255, cb = rgb & 255;
    for (int y = ymin; y <= ymax; ++y) {
        for (int x = xmin; x <= xmax; ++x) {
            const double px = x + 0.5 - ax, py = y + 0.5 - ay;
            double t = len2 > 0 ? (px * dx + py * dy) / len2 : 0;
            t = t < 0 ? 0 : t > 1 ? 1 : t;
            const double ex = px - t * dx, ey = py - t * dy;
            double cov = r + 0.5 - std::sqrt(ex * ex + ey * ey);
            if (cov <= 0) continue;
            if (cov > 1) cov = 1;
            const double a = cov * alpha;
            uint8_t* p = rgba + (size_t(y) * size_t(w) + size_t(x)) * 4;
            p[0] = uint8_t(p[0] + (cr - p[0]) * a + 0.5);
            p[1] = uint8_t(p[1] + (cg - p[1]) * a + 0.5);
            p[2] = uint8_t(p[2] + (cb - p[2]) * a + 0.5);
        }
    }
}

// An edge is a cubic Hermite curve between its nodes with the engine's own
// tangents (metres), so curves follow the track, not the chord.
static void MinimapDrawEdge(uint8_t* rgba, const MinimapRequest& q, const MinimapNetEdge& e,
                            double r, uint32_t rgb, double alpha) {
    const double sx = q.w / (q.x1 - q.x0), sy = q.h / (q.y1 - q.y0);
    // The Bezier control points of the same cubic bound it: skip edges off the picture.
    const double c1x = e.x0 + e.tx0 / 3.0, c1y = e.y0 + e.ty0 / 3.0, c2x = e.x1 - e.tx1 / 3.0, c2y = e.y1 - e.ty1 / 3.0;
    const double minX = (std::min)((std::min)(double(e.x0), double(e.x1)), (std::min)(c1x, c2x));
    const double maxX = (std::max)((std::max)(double(e.x0), double(e.x1)), (std::max)(c1x, c2x));
    const double minY = (std::min)((std::min)(double(e.y0), double(e.y1)), (std::min)(c1y, c2y));
    const double maxY = (std::max)((std::max)(double(e.y0), double(e.y1)), (std::max)(c1y, c2y));
    if ((maxX - q.x0) * sx < -3 || (minX - q.x0) * sx > q.w + 3 || (maxY - q.y0) * sy < -3 || (minY - q.y0) * sy > q.h + 3)
        return;
    const double chord = std::hypot((e.x1 - e.x0) * sx, (e.y1 - e.y0) * sy);
    int steps = chord < 3 ? 1 : int(std::ceil(chord / 3));
    if (steps > 24) steps = 24;
    double px = (e.x0 - q.x0) * sx, py = (e.y0 - q.y0) * sy;
    for (int i = 1; i <= steps; ++i) {
        const double t = double(i) / steps, t2 = t * t, t3 = t2 * t;
        const double h00 = 2 * t3 - 3 * t2 + 1, h10 = t3 - 2 * t2 + t, h01 = -2 * t3 + 3 * t2, h11 = t3 - t2;
        const double nx = (h00 * e.x0 + h10 * e.tx0 + h01 * e.x1 + h11 * e.tx1 - q.x0) * sx;
        const double ny = (h00 * e.y0 + h10 * e.ty0 + h01 * e.y1 + h11 * e.ty1 - q.y0) * sy;
        MinimapStroke(rgba, q.w, q.h, px, py, nx, ny, r, rgb, alpha);
        px = nx;
        py = ny;
    }
}

// Roads under tracks under stations. Roads keep their class colours (towns
// read as street patterns); tracks and stations take their owner's palette
// colour. Nothing is drawn unless the cached network is the one requested.
struct MinimapStyle { double r; uint32_t rgb; double alpha; };
static const MinimapStyle kMinimapRoadStyles[3] = {
    { 0.45, 0xd8d3c8, 0.70 },   // urban
    { 0.55, 0xbfb9a9, 0.90 },   // country
    { 0.85, 0xf0cd5a, 1.00 },   // highway
};
static const MinimapStyle kMinimapTrackStyle = { 0.75, 0x3a2e28, 1.0 };
static const uint32_t kMinimapStationDefaults[4] = { 0xf2f2f2, 0xf2f2f2, 0x9ad0ff, 0xffffff };

static size_t MinimapDrawNetwork(uint8_t* rgba, const MinimapRequest& q) {
    if (!q.layers || !q.net) return 0;
    size_t drawn = 0;
    AcquireSRWLockShared(&g_minimapNetLock);
    const MinimapNet& net = g_minimapNet;
    if (net.id == q.net) {
        const auto hidden = [&](int colour) { return colour >= 0 && ((q.hide >> colour) & 1) != 0; };
        const auto paint = [&](int colour, uint32_t fallback) {
            return colour >= 0 && net.paletteSet[colour] ? net.palette[colour] : fallback;
        };
        if (q.layers & MINIMAP_LAYER_ROADS)
            for (int cls = MINIMAP_EDGE_URBAN; cls <= MINIMAP_EDGE_HIGHWAY; ++cls)
                for (const auto& e : net.edges)
                    if (e.cls == cls && !hidden(e.colour)) {
                        const auto& s = kMinimapRoadStyles[cls];
                        MinimapDrawEdge(rgba, q, e, s.r, s.rgb, s.alpha);
                        ++drawn;
                    }
        if (q.layers & MINIMAP_LAYER_TRACKS)
            for (const auto& e : net.edges)
                if (e.cls == MINIMAP_EDGE_TRACK && !hidden(e.colour)) {
                    MinimapDrawEdge(rgba, q, e, kMinimapTrackStyle.r, paint(e.colour, kMinimapTrackStyle.rgb),
                                    kMinimapTrackStyle.alpha);
                    ++drawn;
                }
        if (q.layers & MINIMAP_LAYER_STATIONS) {
            const double sx = q.w / (q.x1 - q.x0), sy = q.h / (q.y1 - q.y0);
            for (const auto& s : net.stations) {
                if (hidden(s.colour)) continue;
                const double cx = (s.x - q.x0) * sx, cy = (s.y - q.y0) * sy;
                double hx = s.ux * s.half * sx, hy = s.uy * s.half * sy;
                const double hl = std::hypot(hx, hy);
                if (hl > 8) { hx *= 8 / hl; hy *= 8 / hl; }
                MinimapStroke(rgba, q.w, q.h, cx - hx, cy - hy, cx + hx, cy + hy, 3.1, 0x1a1a1a, 0.9);
                MinimapStroke(rgba, q.w, q.h, cx - hx, cy - hy, cx + hx, cy + hy, 2.2,
                              paint(s.colour, kMinimapStationDefaults[s.cls]), 1.0);
                ++drawn;
            }
        }
    }
    ReleaseSRWLockShared(&g_minimapNetLock);
    return drawn;
}

// A token's payload (after its header line) replaces the cached network under
// the request's net id. Returns true if a payload was present and accepted.
static bool MinimapAcceptPayload(const char* data, size_t size, const MinimapRequest& req, MinimapNet* summary) {
    const size_t header = MinimapHeaderLength(data, size);
    if (header + 1 >= size || req.net == 0) return false;
    MinimapNet parsed;
    parsed.id = req.net;
    MinimapParseNetwork(data + header + 1, data + size, &parsed);
    if (summary) {
        summary->id = parsed.id;
        summary->rejected = parsed.rejected;
    }
    AcquireSRWLockExclusive(&g_minimapNetLock);
    g_minimapNet = std::move(parsed);
    if (summary) {
        summary->edges.resize(g_minimapNet.edges.size());
        summary->stations.resize(g_minimapNet.stations.size());
    }
    ReleaseSRWLockExclusive(&g_minimapNetLock);
    return true;
}

// malloc'd RGBA8 for `r`, or nullptr when the terrain cannot be read.
static uint8_t* MinimapRender(void* terrain, const MinimapRequest& r, MinimapTerrain* info) {
    MinimapTerrain m{};
    if (!MinimapReadTerrain(terrain, &m)) return nullptr;
    const size_t n = size_t(r.w) * size_t(r.h);
    float* hts = static_cast<float*>(malloc(n * sizeof(float)));
    uint8_t* rgba = static_cast<uint8_t*>(malloc(n * 4));
    if (!hts || !rgba) {
        free(hts);
        free(rgba);
        return nullptr;
    }
    MinimapSampleHeights(m, r, hts);
    MinimapShade(m, r, hts, rgba);
    free(hts);
    MinimapDrawNetwork(rgba, r);
    if (info) *info = m;
    return rgba;
}

// ---- live wiring ----------------------------------------------------------
// *(CGameUI+0x450) is the accessor object (loaded at 0x5a2999; every caller of
// 0x8bb7f0 passes the ADDRESS of such a field, which it dereferences once).
// Its vtbl[1] returns the UI game state, whose +0x20 is the CTerrain
// (0x8bb820). Code pointers are range-checked before the virtual call.
static void* MinimapTerrainFromGameUI(void* ui) {
    if (!ui) return nullptr;
    void* acc = nullptr;
    memcpy(&acc, static_cast<const uint8_t*>(ui) + 0x450, sizeof acc);
    if (!acc) return nullptr;
    uintptr_t vtbl = 0;
    memcpy(&vtbl, acc, sizeof vtbl);
    if (vtbl < g_minimapImageLo || vtbl + 16 > g_minimapImageHi) return nullptr;
    uintptr_t fn = 0;
    memcpy(&fn, reinterpret_cast<const void*>(vtbl + 8), sizeof fn);
    if (fn < g_minimapImageLo || fn >= g_minimapImageHi) return nullptr;
    void* state = reinterpret_cast<void* (__fastcall*)(void*)>(fn)(acc);
    if (!state) return nullptr;
    void* terrain = nullptr;
    memcpy(&terrain, static_cast<const uint8_t*>(state) + 0x20, sizeof terrain);
    return terrain;
}

// A small image the game always has: written over the token inside the
// string's own buffer, so the by-value string keeps stock ownership and the
// original sees an ordinary icon path. The raw texture then replaces it.
static const char kMinimapPlaceholder[] = "ui/icons/main-menu/map_town.tga";

static void* __fastcall MinimapSetImagePathDetour(void* imageView, MinimapMsvcString* path, uint64_t flag) {
    if (!path || !MinimapIsToken(MinimapStringData(path), path->size))
        return g_minimapSetImagePath(imageView, path, flag);
    char* data = MinimapStringData(path);
    MinimapRequest req{};
    const bool parsed = MinimapParse(data, size_t(path->size), &req);
    // The payload is read before the placeholder overwrites the string's start.
    MinimapNet summary;
    if (parsed && MinimapAcceptPayload(data, size_t(path->size), req, &summary))
        H->log("minimap: network %llu: %zu edges, %zu stations%s", (unsigned long long)req.net,
               summary.edges.size(), summary.stations.size(), summary.rejected ? " (some lines rejected)" : "");
    const size_t placeholder = sizeof kMinimapPlaceholder - 1;
    if (path->cap >= placeholder) {
        memcpy(data, kMinimapPlaceholder, placeholder + 1);
        path->size = placeholder;
    } else {
        data[0] = 0;
        path->size = 0;
    }
    void* result = g_minimapSetImagePath(imageView, path, flag);   // consumes the string
    if (!parsed) {
        H->log("minimap: malformed request token -- expected bigmap:minimap?x0=&y0=&x1=&y1=&w=&h=");
        return result;
    }
    LARGE_INTEGER freq{}, t0{}, t1{};
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&t0);
    MinimapTerrain info{};
    uint8_t* rgba = MinimapRender(MinimapTerrainFromGameUI(g_minimapGameUI), req, &info);
    if (!rgba) {
        H->log("minimap: no readable terrain for this game UI -- image left blank");
        return result;
    }
    struct { uint8_t* begin; uint8_t* end; uint8_t* cap; } vec = {
        rgba, rgba + size_t(req.w) * size_t(req.h) * 4, rgba + size_t(req.w) * size_t(req.h) * 4 };
    g_minimapSetImageRaw(imageView, 4, req.w, req.h, &vec, 1);     // uploads synchronously
    free(rgba);
    QueryPerformanceCounter(&t1);
    H->log("minimap: rendered %dx%d px of (%.0f,%.0f)-(%.0f,%.0f) m in %.1f ms "
           "(tiles %dx%d from (%d,%d), %d samples/tile, %.2f m/sample, water %.1f m)",
           req.w, req.h, req.x0, req.y0, req.x1, req.y1,
           double(t1.QuadPart - t0.QuadPart) * 1000.0 / double(freq.QuadPart),
           info.w, info.h, info.x0, info.y0, info.perTile, double(info.resX), double(info.water));
    return result;
}

// mov rax, &slot; mov [rax], rcx; mov rax, &trampoline; jmp [rax]
// Saves `this` and continues into the original without touching the stack or
// any argument register, so CreateConstructionMenu's arity does not matter.
static uint8_t* MinimapBuildCaptureThunk(void** slot, void** trampoline) {
    uint8_t code[25] = { 0x48, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0,   0x48, 0x89, 0x08,
                         0x48, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0,   0xff, 0x20 };
    memcpy(code + 2, &slot, 8);
    memcpy(code + 15, &trampoline, 8);
    uint8_t* p = static_cast<uint8_t*>(VirtualAlloc(nullptr, sizeof code, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE));
    if (!p) return nullptr;
    memcpy(p, code, sizeof code);
    DWORD old = 0;
    if (!VirtualProtect(p, sizeof code, PAGE_EXECUTE_READ, &old)) {
        VirtualFree(p, 0, MEM_RELEASE);
        return nullptr;
    }
    FlushInstructionCache(GetCurrentProcess(), p, sizeof code);
    return p;
}

// ---- the game script ------------------------------------------------------
static const char kMinimapScriptMarker[] = "-- tpf2_bigmap minimap";
enum {
    MINIMAP_SCRIPT_ERR = -1, MINIMAP_SCRIPT_ABSENT = 0, MINIMAP_SCRIPT_REMOVED = 1,
    MINIMAP_SCRIPT_ALREADY = 2, MINIMAP_SCRIPT_WRITTEN = 3, MINIMAP_SCRIPT_FOREIGN = 4
};
static wchar_t g_minimapScriptPathOverride[MAX_PATH] = L"";

static char* MinimapScriptText(size_t* len) {
    size_t total = 0;
    for (const char* part : kMinimapLuaParts) total += strlen(part);
    char* text = static_cast<char*>(malloc(total + 1));
    if (!text) return nullptr;
    size_t at = 0;
    for (const char* part : kMinimapLuaParts) {
        const size_t n = strlen(part);
        memcpy(text + at, part, n);
        at += n;
    }
    text[at] = 0;
    *len = at;
    return text;
}

// want: make `path` our script. !want: remove it. A file there that we did not
// write (no marker on its first line) is never touched.
static int SyncMinimapScript(const wchar_t* path, bool want) {
    const DWORD attrs = GetFileAttributesW(path);
    const bool exists = attrs != INVALID_FILE_ATTRIBUTES && !(attrs & FILE_ATTRIBUTE_DIRECTORY);
    char* cur = nullptr;
    size_t curLen = 0;
    if (exists && !ReadWholeFile(path, &cur, &curLen)) return MINIMAP_SCRIPT_ERR;
    const size_t markerLen = sizeof kMinimapScriptMarker - 1;
    if (exists && (curLen < markerLen || memcmp(cur, kMinimapScriptMarker, markerLen) != 0)) {
        free(cur);
        return MINIMAP_SCRIPT_FOREIGN;
    }
    int rc;
    if (!want) {
        rc = !exists ? MINIMAP_SCRIPT_ABSENT : DeleteFileW(path) ? MINIMAP_SCRIPT_REMOVED : MINIMAP_SCRIPT_ERR;
    } else {
        size_t len = 0;
        char* text = MinimapScriptText(&len);
        if (!text) rc = MINIMAP_SCRIPT_ERR;
        else if (exists && curLen == len && memcmp(cur, text, len) == 0) rc = MINIMAP_SCRIPT_ALREADY;
        else rc = WriteWholeFile(path, text, len) ? MINIMAP_SCRIPT_WRITTEN : MINIMAP_SCRIPT_ERR;
        free(text);
    }
    free(cur);
    return rc;
}

static const char* MinimapScriptResultText(int rc) {
    switch (rc) {
    case MINIMAP_SCRIPT_ABSENT:  return "not present";
    case MINIMAP_SCRIPT_REMOVED: return "removed";
    case MINIMAP_SCRIPT_ALREADY: return "up to date";
    case MINIMAP_SCRIPT_WRITTEN: return "written";
    case MINIMAP_SCRIPT_FOREIGN: return "a file we did not write is in the way -- left alone";
    default:                     return "could not be read or written";
    }
}

// <game>\res\config\game_script\bigmap_minimap.lua for a game folder.
static bool MinimapScriptPathIn(const wchar_t* gameDir, wchar_t* out, size_t cch) {
    return _snwprintf_s(out, cch, _TRUNCATE, L"%s\\res\\config\\game_script\\bigmap_minimap.lua", gameDir) > 0;
}

static int SyncGameMinimapScript(bool want) {
    wchar_t path[MAX_PATH];
    if (g_minimapScriptPathOverride[0]) {
        wcscpy_s(path, g_minimapScriptPathOverride);
    } else {
        wchar_t exe[MAX_PATH];
        const DWORD n = GetModuleFileNameW(nullptr, exe, MAX_PATH);
        wchar_t* slash = (n && n < MAX_PATH) ? wcsrchr(exe, L'\\') : nullptr;
        if (!slash) {
            H->log("minimap: cannot work out the game folder -- script left alone");
            return MINIMAP_SCRIPT_ERR;
        }
        *slash = 0;
        if (!MinimapScriptPathIn(exe, path, MAX_PATH)) return MINIMAP_SCRIPT_ERR;
    }
    const int rc = SyncMinimapScript(path, want);
    // Quiet when the minimap is off and was never installed.
    if (want || rc != MINIMAP_SCRIPT_ABSENT)
        H->log("minimap: game script %s", MinimapScriptResultText(rc));
    return rc;
}

// ---- install --------------------------------------------------------------
static const uint8_t kMinimapSetImagePathBytes[20] = {0x40,0x53,0x56,0x57,0x48,0x81,0xec,0x90,0x00,0x00,0x00,0x48,0xc7,0x44,0x24,0x20,0xfe,0xff,0xff,0xff};
static const uint8_t kMinimapCreateMenuBytes[20] = {0x40,0x55,0x56,0x57,0x41,0x54,0x41,0x55,0x41,0x56,0x41,0x57,0x48,0x8d,0xac,0x24,0xc0,0xfa,0xff,0xff};
static const uint8_t kMinimapSetImageRawBytes[28] = {0x40,0x55,0x53,0x56,0x57,0x41,0x54,0x41,0x55,0x41,0x56,0x41,0x57,0x48,0x8d,0xac,0x24,0x48,0xff,0xff,0xff,0x48,0x81,0xec,0xb8,0x01,0x00,0x00};
// Through the empty-cell check: pins the tile grid header (*(+0x18): x0 +0,
// y0 +4, W +8, cells +0x10), the 0x28-byte cell and the packed tile argument.
static const uint8_t kMinimapBaseGetVerticesBytes[60] = {0x40,0x53,0x48,0x83,0xec,0x20,0x4c,0x8b,0x41,0x18,0x48,0x8b,0xc2,0x48,0xc1,0xe8,0x20,0x48,0x8b,0xd9,0x41,0x2b,0x40,0x04,0x41,0x0f,0xaf,0x40,0x08,0x41,0x2b,0x00,0x03,0xc2,0x48,0x98,0x48,0x8d,0x14,0x80,0x49,0x8b,0x40,0x10,0x8b,0x0c,0xd0,0x89,0x4c,0x24,0x30,0x83,0xf9,0xff,0x0f,0x84,0xa8,0x00,0x00,0x00};
static const uint8_t kMinimapAccessorBytes[10] = {0x48,0x8b,0x09,0x48,0x8b,0x01,0x48,0xff,0x60,0x08};
static const uint8_t kMinimapTerrainPtrBytes[18] = {0x48,0x83,0xec,0x28,0xe8,0xc7,0xff,0xff,0xff,0x48,0x8b,0x40,0x20,0x48,0x83,0xc4,0x28,0xc3};
static const uint8_t kMinimapGameUIAccessorLoadBytes[7] = {0x48,0x8b,0x99,0x50,0x04,0x00,0x00};
static const uint8_t kMinimapLevelsGetterBytes[4] = {0x8b,0x41,0x28,0xc3};
static const uint8_t kMinimapResolutionGetterBytes[13] = {0x8b,0x41,0x34,0xf2,0x0f,0x10,0x41,0x2c,0xf2,0x0f,0x11,0x02,0x89};
static const uint8_t kMinimapOffsetGetterBytes[6] = {0xf3,0x0f,0x10,0x41,0x3c,0xc3};
static const uint8_t kMinimapWaterGetterBytes[6] = {0xf3,0x0f,0x10,0x41,0x40,0xc3};
static const uint8_t kMinimapTileRectGetterBytes[8] = {0x4c,0x8b,0x41,0x18,0x41,0x8b,0x40,0x08};

static bool MinimapVerifySites() {
    static const struct { uintptr_t rva; const uint8_t* bytes; uint32_t len; } sites[] = {
        { 0x22b4610, kMinimapSetImagePathBytes, sizeof kMinimapSetImagePathBytes },
        { 0x5a2900, kMinimapCreateMenuBytes, sizeof kMinimapCreateMenuBytes },
        { 0x22b4350, kMinimapSetImageRawBytes, sizeof kMinimapSetImageRawBytes },
        { 0x33d130, kMinimapBaseGetVerticesBytes, sizeof kMinimapBaseGetVerticesBytes },
        { 0x8bb7f0, kMinimapAccessorBytes, sizeof kMinimapAccessorBytes },
        { 0x8bb820, kMinimapTerrainPtrBytes, sizeof kMinimapTerrainPtrBytes },
        { 0x5a2999, kMinimapGameUIAccessorLoadBytes, sizeof kMinimapGameUIAccessorLoadBytes },
        { 0x33d270, kMinimapLevelsGetterBytes, sizeof kMinimapLevelsGetterBytes },
        { 0x33d280, kMinimapResolutionGetterBytes, sizeof kMinimapResolutionGetterBytes },
        { 0x33d560, kMinimapOffsetGetterBytes, sizeof kMinimapOffsetGetterBytes },
        { 0x33d7f0, kMinimapWaterGetterBytes, sizeof kMinimapWaterGetterBytes },
        { 0x33d540, kMinimapTileRectGetterBytes, sizeof kMinimapTileRectGetterBytes },
    };
    for (const auto& s : sites)
        if (!H->verifyBytes(s.rva, s.bytes, s.len)) return false;
    return true;
}

// The loaded image's address range, for the vtable sanity check.
static bool MinimapImageRange(uintptr_t base, uintptr_t* lo, uintptr_t* hi) {
    const auto dos = reinterpret_cast<const IMAGE_DOS_HEADER*>(base);
    if (!base || dos->e_magic != IMAGE_DOS_SIGNATURE) return false;
    const auto nt = reinterpret_cast<const IMAGE_NT_HEADERS64*>(base + dos->e_lfanew);
    if (nt->Signature != IMAGE_NT_SIGNATURE) return false;
    *lo = base;
    *hi = base + nt->OptionalHeader.SizeOfImage;
    return true;
}

static bool InstallMinimap() {
    if (!g_minimap || g_gog) {
        if (g_minimap) H->log("minimap: Steam 35924 only; OFF");
        SyncGameMinimapScript(false);
        return false;
    }
    if (!MinimapVerifySites()) {
        H->log("minimap: Steam 35924 byte mismatch; OFF");
        SyncGameMinimapScript(false);
        return false;
    }
    const uintptr_t base = H->moduleBase();
    if (!MinimapImageRange(base, &g_minimapImageLo, &g_minimapImageHi)) {
        H->log("minimap: cannot read the game image headers; OFF");
        SyncGameMinimapScript(false);
        return false;
    }
    g_minimapSetImageRaw = reinterpret_cast<MinimapSetImageRawFn>(base + 0x22b4350);
    g_minimapBaseGetVertices = reinterpret_cast<MinimapVerticesFn>(base + 0x33d130);
    // Capture first: the image hook is useless without a game UI to read from.
    uint8_t* thunk = MinimapBuildCaptureThunk(&g_minimapGameUI, &g_minimapCreateMenuTrampoline);
    const bool capture = thunk && H->installHook(base + 0x5a2900, reinterpret_cast<void*>(thunk),
        sizeof kMinimapCreateMenuBytes, &g_minimapCreateMenuTrampoline) != 0;
    const bool image = capture && H->installHook(base + 0x22b4610, reinterpret_cast<void*>(&MinimapSetImagePathDetour),
        sizeof kMinimapSetImagePathBytes, reinterpret_cast<void**>(&g_minimapSetImagePath)) != 0;
    if (!capture || !image) {
        // A lone capture hook only records a pointer; without the script nothing uses it.
        H->log("minimap: hook failed (game UI capture %s, image %s); OFF",
               capture ? "ok" : "FAILED", image ? "ok" : "FAILED");
        SyncGameMinimapScript(false);
        return false;
    }
    const int rc = SyncGameMinimapScript(true);
    const bool ok = rc == MINIMAP_SCRIPT_WRITTEN || rc == MINIMAP_SCRIPT_ALREADY;
    H->log("minimap: %s -- the map button is on the main toolbar in game", ok ? "enabled" : "hooks installed but no script");
    return ok;
}

// ---- offline test entries (tools/test_minimap.py) -------------------------
extern "C" __declspec(dllexport)
int BigmapTestMinimapParse(const char* token, double* rect, int* size, double* relief) {
    MinimapRequest r{};
    if (!MinimapParse(token, strlen(token), &r)) return 0;
    rect[0] = r.x0; rect[1] = r.y0; rect[2] = r.x1; rect[3] = r.y1;
    size[0] = r.w; size[1] = r.h;
    *relief = r.relief;
    return 1;
}
extern "C" __declspec(dllexport)
int BigmapTestMinimapParseExtra(const char* token, int* layers, uint64_t* net, uint64_t* hide) {
    MinimapRequest r{};
    if (!MinimapParse(token, strlen(token), &r)) return 0;
    *layers = r.layers; *net = r.net; *hide = r.hide;
    return 1;
}
// Accepts a token's payload exactly as the detour does. out: edges, stations, rejected lines.
extern "C" __declspec(dllexport)
int BigmapTestMinimapAcceptNetwork(const char* token, uint64_t length, uint64_t* out) {
    MinimapRequest r{};
    if (!MinimapParse(token, size_t(length), &r)) return 0;
    MinimapNet summary;
    if (!MinimapAcceptPayload(token, size_t(length), r, &summary)) return 0;
    out[0] = summary.edges.size(); out[1] = summary.stations.size(); out[2] = summary.rejected;
    return 1;
}
extern "C" __declspec(dllexport)
int BigmapTestMinimapRender(void* terrain, MinimapVerticesFn verts, const char* token, uint8_t* out, uint64_t outBytes) {
    MinimapRequest r{};
    if (!MinimapParse(token, strlen(token), &r) || outBytes < uint64_t(r.w) * uint64_t(r.h) * 4) return 0;
    const auto old = g_minimapBaseGetVertices;
    g_minimapBaseGetVertices = verts;
    uint8_t* rgba = MinimapRender(terrain, r, nullptr);
    g_minimapBaseGetVertices = old;
    if (!rgba) return 0;
    memcpy(out, rgba, size_t(r.w) * size_t(r.h) * 4);
    free(rgba);
    return 1;
}
extern "C" __declspec(dllexport)
int BigmapTestMinimapHeights(void* terrain, MinimapVerticesFn verts, const char* token, float* out, uint64_t count) {
    MinimapRequest r{};
    MinimapTerrain m{};
    if (!MinimapParse(token, strlen(token), &r) || count < uint64_t(r.w) * uint64_t(r.h) || !MinimapReadTerrain(terrain, &m))
        return 0;
    const auto old = g_minimapBaseGetVertices;
    g_minimapBaseGetVertices = verts;
    MinimapSampleHeights(m, r, out);
    g_minimapBaseGetVertices = old;
    return 1;
}
extern "C" __declspec(dllexport)
void* BigmapTestMinimapTerrainFromGameUI(void* ui, uintptr_t lo, uintptr_t hi) {
    const uintptr_t oldLo = g_minimapImageLo, oldHi = g_minimapImageHi;
    g_minimapImageLo = lo; g_minimapImageHi = hi;
    void* t = MinimapTerrainFromGameUI(ui);
    g_minimapImageLo = oldLo; g_minimapImageHi = oldHi;
    return t;
}
extern "C" __declspec(dllexport)
void* BigmapTestMinimapSetImage(const Tpf2mpHost* host, void* imageView, MinimapMsvcString* path, uint64_t flag,
    MinimapSetImagePathFn original, MinimapSetImageRawFn raw, MinimapVerticesFn verts,
    void* gameUI, uintptr_t lo, uintptr_t hi) {
    const auto oldH = H;
    H = host;
    g_minimapSetImagePath = original; g_minimapSetImageRaw = raw; g_minimapBaseGetVertices = verts;
    g_minimapGameUI = gameUI; g_minimapImageLo = lo; g_minimapImageHi = hi;
    void* result = MinimapSetImagePathDetour(imageView, path, flag);
    H = oldH;
    return result;
}
extern "C" __declspec(dllexport)
void* BigmapTestMinimapCaptureThunk(void** slot, void** trampoline) {
    return MinimapBuildCaptureThunk(slot, trampoline);
}
extern "C" __declspec(dllexport)
int BigmapTestSyncMinimapScript(const wchar_t* path, int want) { return SyncMinimapScript(path, want != 0); }
extern "C" __declspec(dllexport)
uint64_t BigmapTestMinimapScriptText(char* out, uint64_t cap) {
    size_t len = 0;
    char* text = MinimapScriptText(&len);
    if (!text) return 0;
    if (out && cap > len) memcpy(out, text, len + 1);
    free(text);
    return len;
}
extern "C" __declspec(dllexport)
int BigmapTestInstallMinimap(const Tpf2mpHost* host, int gog, int enabled, const wchar_t* scriptPath) {
    const auto oldH = H;
    const bool oldGog = g_gog, oldOn = g_minimap;
    H = host; g_gog = gog != 0; g_minimap = enabled != 0;
    wcscpy_s(g_minimapScriptPathOverride, scriptPath ? scriptPath : L"");
    const bool ok = InstallMinimap();
    g_minimapScriptPathOverride[0] = 0;
    H = oldH; g_gog = oldGog; g_minimap = oldOn;
    return ok;
}
